# Generated by Django 4.0.2 on 2022-02-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalOp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('Age', models.DecimalField(decimal_places=0, max_digits=2)),
                ('Email', models.EmailField(max_length=254)),
                ('BP', models.CharField(max_length=264)),
                ('gender1', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=264, verbose_name='Gender')),
                ('YEARS1', models.DateField(verbose_name='Date of Birth')),
                ('WEIGHT1', models.CharField(choices=[('1', 'Less Than 20'), ('2', '20-40'), ('3', '40-60'), ('4', '60-80'), ('5', 'Greater Than 80')], max_length=264, verbose_name='Weight')),
                ('PBFC1', models.CharField(choices=[('1', 'Fever'), ('2', 'Cold and Cough'), ('3', 'Headache'), ('4', 'Stomach Ache'), ('5', 'Vision Problem'), ('6', 'Dental Issue'), ('7', 'ENT'), ('8', 'Heart Problem'), ('9', 'Liver Issue'), ('10', 'Digestion Problem'), ('11', 'Others')], max_length=264, verbose_name='Problems Facing')),
                ('DRFC1', models.CharField(choices=[('1', 'Dr. B.S. Gupta'), ('2', 'Dr. Anantha Subramaniam'), ('3', 'Dr. Jawahar Ticku '), ('4', 'Dr. S.K. Agarwal'), ('5', 'Dr. Bhagwan Swaroop Gupta'), ('7', 'Dr. Rajesh Patel.'), ('8', 'Dr. Yaghyavalk Sharma.'), ('9', 'Dr. Prem Sanker.'), ('10', 'Dr. Satyendra Chaudhary.'), ('12', 'Dr. Suhail Farooq.'), ('13', 'Dr. Gaurav Mittal.')], max_length=264, verbose_name='Doctor to be Reffered')),
            ],
            options={
                'db_table': 'modelForms',
            },
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
