# Generated by Django 4.0.2 on 2022-02-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalOp', '0002_modelforms_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modelforms',
            table=None,
        ),
    ]
