# Generated by Django 4.0.2 on 2022-02-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalOp', '0003_alter_modelforms_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelforms',
            name='gender1',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=264, verbose_name='Gender'),
        ),
    ]
